-- AlterTable
ALTER TABLE "phase_steps" ALTER COLUMN "planned_start_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "planned_end_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "actual_start_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "actual_end_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "procurement_items" ALTER COLUMN "requirement_created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "quote_requested_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "quote_received_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "order_confirmed_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "payment_settled_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "expected_arrival_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "actual_arrival_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "qc_checked_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "projects" ALTER COLUMN "rough_design_completed_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "planned_start_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "planned_end_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "actual_start_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "actual_end_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "step_status_log" ALTER COLUMN "changed_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3);
